[default]
src = 'src'
out = 'out'
libs = ['lib']
remappings = [
    '@thirdweb-dev/contracts/=lib/contracts/contracts',
    '@erc6551/=lib/reference/',
]


# See more config options https://github.com/foundry-rs/foundry/tree/master/config